@startuml erd

entity Room {
  * RoomNumber : int
  --
  RoomName : varchar(20)
  RoomPrefix : varchar(10)
  RoomSuffix : varchar(10)
}

entity Subject {
  *SubjectID : int
  --
   SubjectName : varchar(20)
}

entity ClassSubject {
  *ClassSubjectID : int
  --
  <u>Teacher : varchar(20) 
  <u>Subject : varchar(20)
  WeeklyHours : int
  RequiresDoublePeriod : bool 
  IsBetterDoublePeriod : bool 
}

entity Teacher {
  *TeacherID : int
  --
  TeacherName : varchar(20)
  NameSymbol : varchar(10)
}

entity RoomTypes {
  *RoomTypeID
  --
  RoomType : varchar(10)
}

entity RequiredRoomTypes {
  <u>SubjectID : int
  ---
  RoomType : varchar(10)
}

entity Room_RoomTypes { 
  <u>RoomNumber : int 
  ---
  RoomType : varchar(10)
}

ClassSubject ||-- Subject
ClassSubject ||-- Teacher

Room }o-- Room_RoomTypes

Subject }o-- RequiredRoomTypes
RequiredRoomTypes }o-- Room

@enduml